version: "3.7"
services:
  app:
    build:
      context: ./
      dockerfile: Dockerfile
    image: laravel
    container_name: my-app
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
    networks:
      - test

  nginx:
    image: nginx:alpine
    container_name: my-app-nginx
    restart: unless-stopped
    ports:
      - 80:80
    volumes:
      - ./nginx/:/etc/nginx/conf.d/
    networks:
      - test

networks:
  test:
    driver: bridge